# Generated by Django 4.1.5 on 2023-01-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='股票名稱')),
                ('code', models.CharField(blank=True, max_length=10, verbose_name='股票代號')),
                ('remark', models.CharField(max_length=50, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='建立時間')),
            ],
            options={
                'db_table': '"stock_lists"',
            },
        ),
    ]
